django_segunda_parte/app_store/urls.py
from django.contrib import admin
from django.urls import path , include


from .views import      StoreListView   \
                    ,   StoreDetailView \
                    ,   StoreCreateView \
                    ,   StoreUpdateView \
                    ,   StoreDeleteView


from .router import router

app_name = "store"

urlpatterns = [
    path("", StoreListView.as_view(), name="all"),
    path("create/", StoreCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", StoreDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", StoreUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", StoreDeleteView.as_view(), name="delete")
]

# -> store_manager.urls.py



urlpatterns += router.urls

django_segunda_parte/store_manager/urls.py
from django.contrib import admin
from django.urls import path, include


from .views import Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("store/",include("app_store.urls"))
]

django_segunda_parte/app_store/models.py
from django.db import models
from django.db.models import Model

# Create your models here.


class Store(Model):
    nombre = models.CharField(max_length=100)
    ubicacion = models.CharField(max_length=100)
    contacto = models.EmailField(max_length= 200,null=False,blank=False)
    fecha_creacion = models.DateField(auto_now=True)

    class Meta:
        db_table = "tiendas_buenos_aires"
    
    def __str__(self):
        return f"La tienda: {self.nombre}, su ubicacion es: {self.ubicacion}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
    
# --> registrar la app en admin.py

django_segunda_parte/app_store/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list      import ListView
from django.views.generic.detail    import DetailView
from django.views.generic.edit      import DeleteView, UpdateView, CreateView


from .models import Store

# Create your views here.


class StoreBaseView(View):
    template_name = 'store.html'
    model = Store
    fields = '__all__'
    success_url = reverse_lazy('store:all')


class StoreListView(StoreBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS Store
    """

class StoreDetailView(StoreBaseView,DetailView):
    template_name = "store_detail.html"

class StoreCreateView(StoreBaseView,CreateView):
    template_name = "store_create.html"
    extra_context = {
        "tipo": "Crear store"
    }


class StoreUpdateView(StoreBaseView,UpdateView):
    template_name = "store_create.html"
    extra_context = {
        "tipo": "Actualizar store"
    }

class StoreDeleteView(StoreBaseView,DeleteView):
    template_name = "store_delete.html"
    extra_context = {
        "tipo": "Borrar store"
    }


# -> app_store.urls.py

django_segunda_parte/store_manager/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    extra_context = {"comision": "23506"}
    template_name = "index.html"

django_segunda_parte/app_store/templates/store.html
{% extends 'base.html' %} {% load static %} {% block content %}

<main>
  <div>
    <h1>Stores</h1>
    <h2><a href="{% url 'store:create' %}">Crear un store</a></h2>
    {% for store in store_list%}
    <div class="list">
      <fieldset>
        <legend>Nombre: {{store.nombre}}</legend>
        <ul>
          <li>Uireccion de la tienda : {{store.ubicacion}}</li>
          <li>contacto: {{store.contacto}}</li>
          <li>Decha de alta : {{store.fecha_creacion}}</li>
        </ul>

        <label for="">Detalles: </label>
        <a href="{% url 'store:detail' store.id %}">👁‍🗨</a>
        <label for="">Borrar: </label>
        <a href="{% url 'store:delete' store.id %}">❌</a>
        <label for="">Editar: </label>
        <a href="{% url 'store:update' store.id %}">👆</a>
      </fieldset>
    </div>

    {% endfor %}
  </div>
</main>

{% endblock %}

django_segunda_parte/app_store/templates/store_create.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <div>
    <form method="post">
      {% csrf_token %}
      <div>{{form.as_div}}</div>
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'store:all' %}">Volvamos al Inicio</a>
  </div>
</main>
{% endblock %}

django_segunda_parte/app_store/templates/store_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<main>
  <div>
    <h1>Estas seguro ue deseas borrar este vino?</h1>
    <h2>{{store.nombre}}</h2>
    <form method="post">
      {% csrf_token %}
      <div>{{form.as_p}}</div>
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'store:all' %}">Cancelar</a>
  </div>
</main>

django_segunda_parte/app_store/templates/store_detail.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>{{store.nombre}}</h1>
    {% for label, value in store.get_fields %}

    <p>{{label | upper}}</p>
    <p>{{value}}</p>

    {% endfor %}

    <a href="{% url 'store:all' %}">BACK</a>
  </div>
</main>

{% endblock%}

django_segunda_parte/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static './css/style.css' %}" />
    <title>Segunda Parte Django</title>
  </head>

  <body>
    <div class="loader">
      <div class="balls"></div>
    </div>

    <header class="header" id="header">
      <nav class="navbar">
        <a href="#top" class="brand">
          <div class="logo"><i class="fa fa-rocket"></i></div>
          <h3>Brand</h3>
        </a>
        <div class="burger" id="burger">
          <span class="burger-line"></span>
          <span class="burger-line"></span>
          <span class="burger-line"></span>
        </div>
        <span class="overlay"></span>
        <div class="menu" id="menu">
          <ul class="menu-inner">
            <li class="menu-item">
              <a class="menu-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="menu-item">
              <a class="menu-link" href="{% url 'store:all' %}">CRUD STORES</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    {% block content %} {% endblock %}
  </body>
  <script src=" https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js "></script>
  <script src="{% static './js/index.js' %}"></script>
</html>

django_segunda_parte/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="particles-js"></div>

<section class="hero" id="top">
    <div class="title">
        <h1 class="intro">
            <span class="magic">
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg>
                </span>
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg>
                </span>
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg></span>

                <span class="magic-text">Codo a Codo </span></span> Comisión {{comision}}
        </h1>
    </div>
</section>

<section class="section">
    <div class="desktop-wrapper">
        <div class="carousel reflect">
            <ul class="carousel__list" data-aos="fade-up" data-aos-duration="1000" data-aos-easing="ease">
                <li class="carousel__item" data-pos="-2"></li>
                <li class="carousel__item" data-pos="-1"></li>
                <li class="carousel__item" data-pos="0"></li>
                <li class="carousel__item" data-pos="1"></li>
                <li class="carousel__item" data-pos="2"></li>
            </ul>
        </div>
    </div>
</section>

{% endblock %}